name: .NET

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: ~/.nuget/packages
                  key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-nuget-
            - name: Setup .NET
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: 5.0.x
            - name: Restore dependencies
              run: dotnet restore
            - name: Build
              run: msbuild /t:Publish /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingeFile=true /p:PackageLocation="FiveHead"
            - name: Build Test
              run: msbuild /t:Publish /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingeFile=true /p:PackageLocation="FiveHead.Tests"
            - name: Publish FiveHead
              uses: actions/upload-artifact@v3
              with:
                  name: FiveHead
                  path: FiveHead
            - name: Publish FiveHead.Tests
              uses: actions/upload-artifact@v3
              with:
                  name: FiveHead.Tests
                  path: FiveHead.Tests
